---

- job:
    name: js-build-ubuntu
    parent: js-build
    nodeset: ubuntu-focal

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - js-build-ubuntu
    gate:
      jobs:
        - js-build-ubuntu
        # TODO: rancher-integration-driver-latest
    # release:
    #  jobs:
    #    # TODO: publish artifacts to OBS
