---

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - js-build
    check-post:
      jobs:
        - rancher-integration-latest
    gate:
      jobs:
        - js-build
        - rancher-integration-latest
    # release:
    #  jobs:
    #    # TODO: publish artifacts to OBS
