---

- project:
    merge_mode: squash-merge
    check:
      jobs:
        - js-build
    gate:
      jobs:
        - js-build
        # TODO: rancher-integration-driver-latest
    release:
      jobs:
        # TODO: publish artifacts to OBS
